Moved conversation to new interfaces
jswistak/automatic-data-analysis pull request #15
Opened 2023-11-20 21:16 UTC by jswistak

2023-11-20 22:29 UTC, FilipKolodziejczyk requested changes

2023-11-20 22:29 UTC, FilipKolodziejczyk commented on main.py
> +        print(f"{Colors.BOLD_BLACK}Assistant: {Colors.END}", end="")
There is a dedicated function for that: 'print_assistant_message'

2023-11-21 16:17 UTC, FilipKolodziejczyk requested changes

2023-11-21 16:17 UTC, FilipKolodziejczyk commented on conversation.py
> +    def _add_to_conversation(self, role: ConversationRolesInternalEnum, content: str) -> None:
Same as below

2023-11-21 16:17 UTC, FilipKolodziejczyk commented on conversation.py
> +        print_message(self._get_last_message(), Colors.PURPLE)
Send message code prints code?

2023-11-21 17:53 UTC, jswistak commented on conversation.py
> +    def format_code_assistant_message(message: str, code_output: str) -> str:
That is not true, we are using this function to forward the message from the `code` assistant to the `analysis` assistant

2023-11-21 17:56 UTC, FilipKolodziejczyk commented on conversation.py
> +    def format_code_assistant_message(message: str, code_output: str) -> str:
Ups. That is true. My bad.

2023-11-21 20:44 UTC, FilipKolodziejczyk approved these changes

2023-11-21 20:44 UTC, merged